### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by islam2hamy** [RikkaApps/WADB#29]
```
FATAL EXCEPTION: main
Process: moe.haruue.wadb, PID: 481
android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class rikka.widget.mainswitchbar.MainSwitchBar
Caused by: android.view.InflateException: Binary XML file line #23: Error inflating class rikka.widget.mainswitchbar.MainSwitchBar
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	at android.view.LayoutInflater.createView(LayoutInflater.java:652)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:812)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:883)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:522)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
	at androidx.preference.d.e(PreferenceGroupAdapter.java:7)
	at androidx.recyclerview.widget.RecyclerView$s.j(RecyclerView.java:120)
	at androidx.recyclerview.widget.LinearLayoutManager$c.c(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.g1(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.R0(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.k0(LinearLayoutManager.java:119)
	at androidx.recyclerview.widget.RecyclerView.v(RecyclerView.java:14)
	at androidx.recyclerview.widget.RecyclerView.t(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.r(CoordinatorLayout.java:59)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:9)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:730)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2390)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2112)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1298)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6437)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
	at android.view.Choreographer.doCallbacks(Choreographer.java:688)
	at android.view.Choreographer.doFrame(Choreographer.java:623)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: android.view.InflateException: Binary XML file line #44: Binary XML file line #44: You must supply a layout_width attribute.
Caused by: java.lang.UnsupportedOperationException: Binary XML file line #44: You must supply a layout_width attribute.
	at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:767)
	at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:7036)
	at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:7218)
	at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:1926)
	at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1824)
	at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1823)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:885)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:886)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:522)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
	at rikka.widget.mainswitchbar.MainSwitchBar.<init>(MainSwitchBar.java:3)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	at android.view.LayoutInflater.createView(LayoutInflater.java:652)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:812)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:883)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:522)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
	at androidx.preference.d.e(PreferenceGroupAdapter.java:7)
	at androidx.recyclerview.widget.RecyclerView$s.j(RecyclerView.java:120)
	at androidx.recyclerview.widget.LinearLayoutManager$c.c(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.g1(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.R0(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.k0(LinearLayoutManager.java:119)
	at androidx.recyclerview.widget.RecyclerView.v(RecyclerView.java:14)
	at androidx.recyclerview.widget.RecyclerView.t(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.r(CoordinatorLayout.java:59)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:9)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:730)
	at android.view.View.layout(View.java:17666)
	at android.view.ViewGroup.layout(ViewGroup.java:5577)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2390)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2112)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1298)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6437)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
	at android.view.Choreographer.doCallbacks(Choreographer.java:688)
	at android.view.Choreographer.doFrame(Choreographer.java:623)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

**Comment by pejfat08-rgb** [comment]
![20230529_090305.jpg](https://github.com/user-attachments/assets/d0b867f9-e78b-4486-a46a-893342a28044)
